# path configuration
path:
  # template --> null if you want to run an entire catalog
  filename: path/to/template.fits
  # folder where templates are stored --> null if you want to run a single template
  catalog: path/to/templates/folder
  # output where visibility table will be saved
  output: path/to/visibility/output.npy
# observation setup
setup:
  # sub altitude below which starts the night (for astronomical darkness set -18)
  twilight: -18
  # min angular separation from Moon 
  moon_sep: 30
  # max moon phase (range 0-1)
  moon_pha: 0.8
  # FoV radius (min angular separation will be added to this)
  fov_rad: 3
  # altitude (lower) thresholds for IRFs ranges
  thresholds:
    - 10
    - 36
    - 57
  # relative IRFs zenith angle
  zenith_angles:
    - 60
    - 40
    - 20
# all sites
sites_list:
  North: Roque de los Muchachos
  South: Paranal
# total grid points (only if use_visibility_table: no)
total_points: 100
# grid points within visibility window
window_points: 10
